SELECT * FROM employee_turnover;
----------------------------------
-- DISCLAIMER : This is a synthetic dataset generated by IBM Data Scientists. Furthermore, this data/analysis includes information such as AGE and GENDER which may provide intersting insight into the topic being researched BUT it should not be used to inform workplace decisions. The analysis made based on this data should also NOT be used as a predictive model to determine employee attrition and instead should be viewed as a snapshot to give insight on potential reasons for employee churn.
----------------------------------
-- Fix age column name

ALTER TABLE employee_turnover
RENAME COLUMN `ï»¿Age` TO `Age`

----------------------------------
-- Hours worked is not given making these sectiones poor variables to use in monetary calculations so there is not need to keep these columns

ALTER TABLE employee_turnover
DROP `HourlyRate`

ALTER TABLE employee_turnover
DROP `DailyRate`

ALTER TABLE employee_turnover
DROP `MonthlyRate`

----------------------------------
-- The dataset does not include any employees under 18. Furthermore, we are going to view the data at each individual age instead of Over/Under 18

ALTER TABLE employee_turnover
DROP `Over18`

----------------------------------
-- Make sure any null values are eliminated

UPDATE employee_turnover SET `Attrition` = 'No' WHERE `Attrition` IS NULL
UPDATE employee_turnover SET `Overtime` = 'No' WHERE `Overtime` IS NULL

----------------------------------
-- (Personal) Find any correlation/breakdown on attrition in relation with Age, Gender and Marital-Status

SELECT Attrition, Age, Gender, MaritalStatus
FROM employee_turnover
WHERE Attrition = "Yes";

SELECT Gender, COUNT(EmployeeCount) AS EmployeeCount
FROM employee_turnover
GROUP BY Gender;
--
	SELECT COUNT(Attrition) AS Employee_Turnover, Age
    FROM employee_turnover
    WHERE Attrition = "Yes"
    GROUP BY Age
    ORDER BY  Employee_Turnover DESC;

    SELECT Gender, COUNT(Attrition) AS Employee_Turnover
    FROM employee_turnover
    WHERE Attrition = "Yes"
    GROUP BY Gender
    ORDER BY  Employee_Turnover DESC;
-- Turnover amognst Male employees is slightly higher at 17% compared to Female employees at 14.80%.
-- We can see that attrition amongst male employees seems highest between the ages of 26 and 32. Employee retention is highest between the ages of 34 and 36.
-- For female empoyees, attrition appears highest between the ages of 29 and 31. Employee retention is highest between the ages of 34 and 38
   
   SELECT COUNT(Attrition) AS Employee_Turnover, MaritalStatus
    FROM employee_turnover
    WHERE Attrition = "Yes"
    GROUP BY MaritalStatus
    ORDER BY  Employee_Turnover DESC;
-- For BOTH Male and Female, single employees have a significantly higher attrition rate compared to married or divorced employees.
    -- MEN:    Single = 26.99%, Married = 13.22%, Divorced = 11.43%
    -- FEMALE: Single = 23.62%, Married = 11.40%, Divorced =  7.69%
    
----------------------------------
-- (Monetary) Find any correlation/breakdown on attrition in relation with Monthly-Income and %Salry-Hike

SELECT Attrition, MonthlyIncome
FROM employee_turnover
WHERE Attrition = "Yes";

SELECT COUNT(Attrition) AS Employee_Turnover, PercentSalaryHike
FROM employee_turnover
WHERE Attrition = "Yes"
GROUP BY PercentSalaryHike
ORDER BY  Employee_Turnover DESC;
-- Positions with lower Monyhly-Income appear to be more prone to employee turnover.
-- Furthermore, it seems that attrition inversly correlates with larger salary hikes.

----------------------------------
-- (Job)  Find any correlation/breakdown on attrition in relation with Job Role, Job-satisfaction, Work-life balance and Performance rating and Monthly-Income

SELECT Attrition, JobRole, JobSatisfaction, WorkLifeBalance, PerformanceRating
FROM employee_turnover
WHERE Attrition = "Yes";

SELECT JobRole, COUNT(EmployeeCount) AS EmployeeCount
FROM employee_turnover
GROUP BY JobRole;
--
	SELECT COUNT(Attrition) AS Employee_Turnover, JobRole, AVG(JobSatisfaction) AS AVG_Satisfaction, AVG(WorkLifeBalance) AS AVG_WorkLifeBalance, AVG(PerformanceRating) AS AVG_PerformanceRating, AVG(MonthlyIncome) AS AVG_MonthlyIncome
	 FROM employee_turnover
	 WHERE Attrition = "Yes"
	 GROUP BY JobRole
	 ORDER BY  Employee_Turnover DESC;
-- * AVGs Scale between 1-5*
-- The 3 lowest monthly paying jobs (by AVG) have the highest attrition amongst all included job roles. 
	-- Relatively similar (perhaps slighlty lower) AVG Job-Satisfaction compared to the 3 highest AVG Monthly paying jobs. 
    -- "Bottom 3" have slighlt better AVG Performance Ratings and a bit more noticibal lower Work-Life Balance
	-- The "Bottom 3" consist of around double the employee count compared to the "Top 3" job roles

----------------------------------
-- (Misc-Factors) Find any correlation/breakdown on attrition in relation with Bussiness Travel, Distance from Home, Education and Education Field

SELECT Attrition, BusinessTravel, DistanceFromHome, Education, EducationField
FROM employee_turnover
WHERE Attrition = "Yes";
--
	SELECT COUNT(Attrition) AS Employee_Turnover, BusinessTravel, AVG(DistanceFromHome) AS AVG_DistanceFromHome
    FROM employee_turnover
    WHERE Attrition = "Yes"
    GROUP BY BusinessTravel
    ORDER BY  Employee_Turnover DESC;
 -- There does not appear to be a clear direct correlation between employee turnover and business travel   
    
    SELECT COUNT(Attrition) AS Employee_Turnover, AVG(DistanceFromHome) AS AVG_DistanceFromHome
    FROM employee_turnover
    WHERE Attrition = "Yes"
    ORDER BY  Employee_Turnover DESC;
    
    SELECT COUNT(Attrition) AS Employee_Retention, AVG(DistanceFromHome) AS AVG_DistanceFromHome
    FROM employee_turnover
    WHERE Attrition = "No"
    ORDER BY  Employee_Retention DESC;
-- When compared to employees retained, employees that left the company, on AVG, worked further from home.

    SELECT COUNT(Attrition) AS Employee_Turnover, EducationField, AVG(Education) AS AVG_EducationLevel
    FROM employee_turnover
    WHERE Attrition = "Yes"
    GROUP BY EducationField
    ORDER BY  Employee_Turnover DESC;
-- *Education Level Scale between 1-5*
	-- Education level does seem to somewhat follow an inverse trend with employee turnover with higher AVG education levels having lower turnover
    
----------------------------------
-- Find any correlation/breakdown on attrition in relation with Years at Company, Years in Current Role and Years since last Promotion

SELECT Attrition, COUNT(Attrition) AS Employee_Count, AVG(YearsAtCompany) AS AVG_YearsAtCompany, AVG(YearsInCurrentRole) AS AVG_YearsInCurrentRole, AVG(YearsSinceLastPromotion) AS AVG_YearsSinceLastPromotion
From employee_turnover
GROUP BY Attrition;
-- Attrition typically occurs among employees around 5 years with the company and under 3 years amongst those in thier current roles
